Map<String, String> sr = {
  "AF": "Avganistan",
  "AX": "Оландска Острва",
  "AL": "Albanija",
  "DZ": "Alžir",
  "AS": "Američka Samoa",
  "AD": "Andora",
  "AO": "Angola",
  "AI": "Ангвила",
  "AG": "Antigva i Barbuda",
  "AR": "Argentina",
  "AM": "Jermenija",
  "AW": "Aruba",
  "AC": "Асенсион ",
  "AU": "Australija",
  "AT": "Austrija",
  "AZ": "Azerbejdžan",
  "BS": "Bahami",
  "BH": "Bahrein",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgija",
  "BZ": "Белизе ",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Butan",
  "BO": "Bolivija",
  "BA": "Bosna i Hercegovina",
  "BW": "Bocvana",
  "BR": "Brazil",
  "IO": "Britanska teritorija Indijskog okeana",
  "VG": "Britanska devičanska ostrva",
  "BN": "Bruneji",
  "BG": "Bugarska",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Kambodža",
  "CM": "Kamerun",
  "CA": "Kanada",
  "CV": "Zelenortska ostrva",
  "BQ": "Karipska Holandija",
  "KY": "Kajmanska ostrva",
  "CF": "Centralnoafrička republika",
  "TD": "Čad",
  "CL": "Čile",
  "CN": "Kina",
  "CX": "Božićna ostrva",
  "CC": "Kokosova ostrva",
  "CO": "Kolumbija",
  "KM": "Komori",
  "CD": "Demokratska republika Kongo",
  "CG": "Republika Kongo",
  "CK": "Kukova ostrva",
  "CR": "Kostarika",
  "CI": "Obala slonovače",
  "HR": "Hrvatska",
  "CU": "Kuba",
  "CW": "Kurasao",
  "CY": "Kipar",
  "CZ": "Češka",
  "DK": "Danska",
  "DJ": "Džibuti",
  "DM": "Dominika",
  "DO": "Dominikanska republika",
  "TL": "Istočni Timor",
  "EC": "Ekvador",
  "EG": "Egipat",
  "SV": "El Salvador",
  "GQ": "Ekvatorijalna Gvineja",
  "ER": "Eritreja",
  "EE": "Estonija",
  "ET": "Etiopija",
  "FK": "Foklanska Ostrva",
  "FO": "Farska ostrva",
  "FJ": "Fidži",
  "FI": "Finska",
  "FR": "Francuska",
  "GF": "Francuska gvajana",
  "PF": "Francuska polineyija",
  "GA": "Gabon",
  "GM": "Gambija",
  "GE": "Gruyija",
  "DE": "Nemačka",
  "GH": "Gana",
  "GI": "Gibraltar",
  "GR": "Grčka",
  "GL": "Grenland",
  "GD": "Grenada",
  "GP": "Gvadalupe",
  "GU": "Guam",
  "GT": "Gvatemala",
  "GG": "Gernyi",
  "GN": "Gvineja",
  "GW": "Gvineja Bisao",
  "GY": "Gvajana",
  "HT": "Haiti",
  "HM": "Herdovo ostrvo i Makdonaldova ostrva",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Mađarska",
  "IS": "Island",
  "IN": "Indija",
  "ID": "Indonezija",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Irska",
  "IM": "Ostrvo Man",
  "IL": "Izrael",
  "IT": "Italija",
  "JM": "Jamajka",
  "JP": "Japan",
  "JE": "Džerzi",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenija",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuvajt",
  "KG": "Kirgistan",
  "LA": "Laos",
  "LV": "Letonija",
  "LB": "Liban",
  "LS": "Lesotho",
  "LR": "Liberija",
  "LY": "Libija",
  "LI": "Lihtenštajn",
  "LT": "Litvanija",
  "LU": "Luksemburg",
  "MO": "Makau",
  "MK": "Makedonija",
  "MG": "Madagaskar",
  "MW": "Malavi",
  "MY": "Malezija",
  "MV": "Maldivi",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Maršalska ostrva",
  "MQ": "Martinik",
  "MR": "Mauritanija",
  "MU": "Mauricijus",
  "YT": "Majote",
  "MX": "Meksiko",
  "FM": "Mikroneyija",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolija",
  "ME": "Crna Gora",
  "MS": "Montserat",
  "MA": "Maroko",
  "MZ": "Mozambik",
  "MM": "Mjanmar",
  "NA": "Namibija",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Holandija",
  "NC": "Nova Kaledonija",
  "NZ": "Novi zeland",
  "NI": "Nikaragva",
  "NE": "Niger",
  "NG": "Nigerija",
  "NU": "Niue",
  "NF": "Ostrvo Norfolk",
  "KP": "Severna Koreja",
  "MP": "Severna Marijanska ostrva",
  "NO": "Norveška",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestinske Teritorije",
  "PA": "Panama",
  "PG": "Papua Nova Gvineja",
  "PY": "Paragvaj",
  "PE": "Peru",
  "PH": "Filipini",
  "PL": "Poljska",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Katar",
  "RE": "Reunion",
  "RO": "Rumunija",
  "RU": "Rusija",
  "RW": "Ruanda",
  "BL": "Sent Bartelemi",
  "SH": "Sveta Helena",
  "KN": "St. Kits",
  "LC": "St. Lucija",
  "MF": "Sveti Martin",
  "PM": "Saint Pjer and Mikelon",
  "VC": "St. Vinsent",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome and Prinsipe",
  "SA": "Saudijska Arabija",
  "SN": "Senegal",
  "RS": "Srbija",
  "SC": "Sejšeli",
  "SL": "Sijera Leone",
  "SG": "Singapor",
  "SX": "Sveti Marting",
  "SK": "Slovačka",
  "SI": "Slovenija",
  "SB": "Solomonska ostrva",
  "SO": "Somalija",
  "ZA": "Južna afrika",
  "GS": "Južna Džordžija i južno Sendvička ostrva",
  "KR": "Južna Koreja",
  "SS": "Južni Sudan",
  "ES": "Španija",
  "LK": "Šri Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SJ": "Svalbard",
  "SZ": "Svayilend",
  "SE": "Švedska",
  "CH": "Švajcarska",
  "SY": "Sirija",
  "TW": "Tajvan",
  "TJ": "Tadžikistan",
  "TZ": "Tanzanija",
  "TH": "Tajland",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad/Tobago",
  "TN": "Tunis",
  "TR": "Turska",
  "TM": "Turkmenistan",
  "TC": "Ostrva Turks i Kaikos",
  "TV": "Tuvalu",
  "VI": "Američka devičanska ostrva",
  "UG": "Uganda",
  "UA": "Ukrajina",
  "AE": "Ujedinjeni Arapski emirati",
  "GB": "Velika Britanija",
  "US": "Sjedinjene Države",
  "UY": "Urugvaj",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatikan",
  "VE": "Venecuela",
  "VN": "Vijetnam",
  "WF": "Valis i Futuna",
  "WW": "Svet",
  "EH": "Zapadna Sahara",
  "YE": "Jemen",
  "ZM": "Zambija",
  "ZW": "Zimbabve",
  "search": "Pretraga",
};
